export const outputLines = [
  { text: "[*] Sedang mengumpulkan id teman...", type: "status" },
  {
    text: "[*] Mengambil 1,525 id teman",
    type: "status",
    highlight: ["1,525"],
  },
  { text: "[*] 1333 id terambil...", type: "status", highlight: ["1333"] },
  {
    text: "[!] Hanya dapat mengambil 1333 id",
    type: "error",
    highlight: ["1333"],
  },
  { text: "[*] Menyimpan hasil daftar Teman...", type: "status" },
  {
    text: "[!] Berhasil meyimpan MBFteman.txt",
    type: "success",
    highlight: ["MBFteman.txt"],
  },
  { text: "[?] Langsung Crack (y/t):y", type: "prompt" },
  { text: "[?] Sandi:pakistan", type: "prompt", password: "pakistan" },
  {
    text: "[*] MengCrack 1333 Akun dengan sandi [pakistan]",
    type: "status",
    highlight: ["1333"],
    passwordBracket: ["pakistan"],
  },
  { text: "[*] Persiapan 100%", type: "status", percentage: ["100%"] },
  { text: "[*] Cracking 100%", type: "status", percentage: ["100%"] },
  { text: "[*] Berhasil 2", type: "success", highlight: ["2"] },
  {
    text: "### 10000708079841 => [pakistan]",
    type: "highlight",
    passwordBracket: ["pakistan"],
  },
  {
    text: "### 10001554361737 => [pakistan]",
    type: "highlight",
    passwordBracket: ["pakistan"],
  },
  { text: "[*] Cekpoint 0", type: "status", highlight: ["0"] },
  { text: "[*] Gagal 1325", type: "error", highlight: ["1325"] },
  { text: "[?] Tidak Puas dengan Hasil,Mau coba lagi (y/t):y", type: "prompt" },
  { text: "[?] Sandi:786786", type: "prompt", password: "786786" },
  {
    text: "[*] MengCrack 1333 Akun dengan sandi [786786]",
    type: "status",
    highlight: ["1333"],
    passwordBracket: ["786786"],
  },
  { text: "[*] Persiapan 100%", type: "status", percentage: ["100%"] },
  { text: "[*] Cracking 100%", type: "status", percentage: ["100%"] },
  { text: "[*] Berhasil 8", type: "success", highlight: ["8"] },
];
